// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import PulltorefreshController from "./pulltorefresh_controller"
application.register("pulltorefresh", PulltorefreshController)

import WebPushController from "./web_push_controller"
application.register("web-push", WebPushController)
