// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutoRefreshController from "./auto_refresh_controller";
application.register("auto-refresh", AutoRefreshController);

import BootstrapTooltipController from "./bootstrap_tooltip_controller";
application.register("bootstrap-tooltip", BootstrapTooltipController);

import ClipboardController from "./clipboard_controller";
application.register("clipboard", ClipboardController);

import HeartbeatController from "./heartbeat_controller";
application.register("heartbeat", HeartbeatController);

import MergedMergeRequestsChartController from "./merged_merge_requests_chart_controller";
application.register("merged-merge-requests-chart", MergedMergeRequestsChartController);

import ThemeSelectorController from "./theme_selector_controller";
application.register("theme-selector", ThemeSelectorController);

import TurboFrameFocusController from "./turbo_frame_focus_controller";
application.register("turbo-frame-focus", TurboFrameFocusController);

import UnreadBadgeController from "./unread_badge_controller";
application.register("unread-badge", UnreadBadgeController);

import WebPushController from "./web_push_controller";
application.register("web-push", WebPushController);
