// This file is auto-generated by ./bin/rails stimulus:manifest:update

// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutoRefreshController from "./auto_refresh_controller";
application.register("auto-refresh", AutoRefreshController);

import BootstrapTooltipController from "./bootstrap_tooltip_controller";
application.register("bootstrap-tooltip", BootstrapTooltipController);

import ClipboardController from "./clipboard_controller";
application.register("clipboard", ClipboardController);

import UnreadBadgeController from "./unread_badge_controller";
application.register("unread-badge", UnreadBadgeController);

import WebPushController from "./web_push_controller";
application.register("web-push", WebPushController);
