shared:
  status:
    mappings:
      BLOCKED_STATUS: "secondary"
      CI_STILL_RUNNING: "primary"
      MERGEABLE: "success"

  pipeline:
    mappings:
      SUCCESS: "success"
      FAILED: "danger"
      RUNNING: "primary"

  labels:
    issue:
      contextual:
        - "workflow::"
    deployment:
      contextual:
        - "Pick into auto-deploy"
    open_merge_requests:
      contextual:
        - "pipeline::"
    workflow:
      prefix: "workflow::"
      mappings:
        "workflow::staging-canary": "info"
        "workflow::canary": "info"
        "workflow::staging": "info"
        "workflow::production": "primary"
        "workflow::post-deploy-db-staging": "info"
        "workflow::post-deploy-db-production": "success"
    notification_rules:
      - required_state: open
        watched_labels:
          - "pipeline::tier-2"
          - "pipeline::tier-3"
      - required_label: backend
        required_state: merged
        watched_labels:
          - "workflow::staging-canary"
          - "workflow::canary"
          - "workflow::staging"
          - "workflow::production"
      - required_label: frontend
        required_state: merged
        watched_labels:
          - "workflow::staging-canary"
          - "workflow::canary"
          - "workflow::staging"
          - "workflow::production"
      - required_label: database
        required_state: merged
        watched_labels:
          - "workflow::post-deploy-db-staging"
          - "workflow::post-deploy-db-production"
      - required_label: documentation
        required_state: merged
        watched_labels:
          - "workflow::production"

# production:
#   dashboard:
#     links:
#       - name: Release Management Grafana dashboard
#         url: https://dashboards.gitlab.net/...
