shared:
  status:
    mappings:
      BLOCKED_STATUS: "secondary"
      CI_STILL_RUNNING: "primary"
      MERGEABLE: "success"

  pipeline:
    mappings:
      SUCCESS: "success"
      FAILED: "danger"
      RUNNING: "primary"

  labels:
    issue:
      contextual:
        - "workflow::"
    deployment:
      contextual:
        - "Pick into auto-deploy"
    open_merge_requests:
      contextual:
        - "pipeline::"
    workflow:
      mappings:
        "workflow::staging-canary":
          class: "info"
          title: "staging-canary"
        "workflow::canary":
          class: "info"
          title: "canary"
        "workflow::staging":
          class: "info"
          title: "staging"
        "workflow::production":
          class: "primary"
          title: "production"
        "workflow::post-deploy-db-staging":
          class: "info"
          title: "post-deploy-db-staging"
        "workflow::post-deploy-db-production":
          class: "success"
          title: "post-deploy-db-production"
    notification_rules:
      - required_state: open
        watched_labels:
          - "pipeline::tier-2"
          - "pipeline::tier-3"
      - required_label: backend
        required_state: merged
        watched_labels:
          - "workflow::staging-canary"
          - "workflow::canary"
          - "workflow::staging"
          - "workflow::production"
      - required_label: frontend
        required_state: merged
        watched_labels:
          - "workflow::staging-canary"
          - "workflow::canary"
          - "workflow::staging"
          - "workflow::production"
      - required_label: database
        required_state: merged
        watched_labels:
          - "workflow::post-deploy-db-staging"
          - "workflow::post-deploy-db-production"
      - required_label: documentation
        required_state: merged
        watched_labels:
          - "workflow::production"
