development:
  periodic_cache_refresh:
    class: ScheduleCacheRefreshJob
    queue: background
    args: []
    schedule: every 5 minutes

production:
  periodic_cache_refresh:
    class: ScheduleCacheRefreshJob
    queue: background
    args: []
    schedule: '0/30 * * * *'
  # periodic_command:
  #   command: "SoftDeletedRecord.due.delete_all"
  #   priority: 2
  #   schedule: at 5am every day
